# Redefintion in class

In [23]:
class Point2D:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __add__(self, pt):
        new_x = self.x + pt.x
        new_y = self.y + pt.y
        return Point2D(new_x, new_y)
    def __str__(self):
        return '({}, {})'.format(self.x, self.y)

In [24]:
p1 = Point2D(3, 5)
p2 = Point2D(-1, 1)

In [25]:
p3 = p1 + p2

In [26]:
print(p1, p2, p3)

(3, 5) (-1, 1) (2, 6)


## Numpy 

In [27]:
import numpy as np

In [30]:
arr1 = np.array([1, 2, 3]) # 차원이나 행렬이랑 똑같은거임
print(arr1, arr1.shape, type(arr1)) 

[1 2 3] (3,) <class 'numpy.ndarray'>


In [31]:
arr2 = np.array([arr1, arr1, arr1, arr1])
print(arr2, arr2.shape, type(arr2))

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]] (4, 3) <class 'numpy.ndarray'>


In [33]:
arr3 = np.array([arr2, arr2])
print(arr3, arr3.shape)

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]] (2, 4, 3)


In [34]:
arr4 = np.array([arr3, arr3])
print(arr4, arr4.shape)

[[[[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]]] (2, 2, 4, 3)


In [35]:
arr4 = np.array([arr3, arr3, arr3])
print(arr4, arr4.shape)

[[[[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]]] (3, 2, 4, 3)


In [38]:
arr = np.array([[1], [1], [1]]) # int arr[3][1]
print(arr, arr.shape)

[[1]
 [1]
 [1]] (3, 1)


In [40]:
arr = np.array([[[1]]]) # int arr[1][1][1]
print(arr, arr.shape)

[[[1]]] (1, 1, 1)


In [41]:
zeros = np.zeros([3, 4])
print(zeros, zeros.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)


In [42]:
len(zeros)

3

In [43]:
ones = np.ones([3, 4])
print(ones, ones.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)


In [48]:
arr = np.arange(12)
# arr = np.arange(12).reshape(3, 4) 으로도 바로 사용가능
print(arr, arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [49]:
arr.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
data = np.random.randn(3, 4) # 난수
print(data, data.shape)

[[-2.05040057 -0.08507569  0.33427989  0.9567396 ]
 [-0.5869624  -1.08158531  0.95173783 -2.4692567 ]
 [-0.38625384 -0.82410884  0.26280764 -0.0408317 ]] (3, 4)


In [65]:
bin = data <= 1

In [68]:
print(bin)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [69]:
data[data <= 1] = 100

In [70]:
print(data)

[[100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]]


## broadcast

In [72]:
data + np.array([1,2,3,4])

array([[101., 102., 103., 104.],
       [101., 102., 103., 104.],
       [101., 102., 103., 104.]])

In [74]:
arr = np.random.randint(2, size=12).reshape(3, 4)
print(arr, arr.shape)

[[1 0 0 0]
 [0 1 1 0]
 [0 1 1 0]] (3, 4)


In [78]:
np.sum(arr, axis = 0), np.sum(arr, axis=1), np.sum(arr)

(array([1, 2, 2, 0]), array([1, 2, 2]), np.int64(5))

In [81]:
np.max(arr, axis = 0), np.max(arr, axis=1), np.max(arr)

(array([2, 2, 1, 2], dtype=int32), array([2, 2, 2], dtype=int32), np.int32(2))

In [82]:
arr = np.random.randint(3, size=12).reshape(3, 4)
print(arr)
np.min(arr, axis = 0), np.min(arr, axis=1), np.min(arr)

[[2 2 0 2]
 [1 1 0 2]
 [2 0 2 0]]


(array([1, 0, 0, 0], dtype=int32), array([0, 0, 0], dtype=int32), np.int32(0))

In [83]:
arr = np.random.randint(3, size=12).reshape(3, 4)
print(arr)
np.mean(arr, axis = 0), np.mean(arr, axis=1), np.mean(arr)

[[2 2 0 2]
 [0 1 0 2]
 [0 1 1 0]]


(array([0.66666667, 1.33333333, 0.33333333, 1.33333333]),
 array([1.5 , 0.75, 0.5 ]),
 np.float64(0.9166666666666666))

In [84]:
arr = np.random.randint(10, size=12).reshape(3, 4)
print(arr)
np.argmax(arr, axis = 0), np.argmax(arr, axis=1), np.argmax(arr)

[[5 3 4 7]
 [0 0 7 2]
 [2 3 7 0]]


(array([0, 0, 1, 0]), array([3, 2, 2]), np.int64(3))

In [85]:
arr = np.random.randint(10, size=12).reshape(3, 4)
print(arr)
np.argmin(arr, axis = 0), np.argmin(arr, axis=1), np.argmin(arr)

[[8 3 8 2]
 [6 9 5 4]
 [3 6 1 8]]


(array([2, 0, 2, 0]), array([3, 3, 2]), np.int64(10))

In [86]:
arr = np.random.randint(4, size = 20)
print(arr, arr.shape)

[2 3 1 3 0 0 0 1 1 0 0 0 2 2 2 0 1 0 0 0] (20,)


In [87]:
np.unique(arr)

array([0, 1, 2, 3], dtype=int32)