In [18]:
import numpy as np

In [19]:
X = np.array([[-1, -1], [-1, 1], [1, -1], [1, 1]])
z = np.array([[-1], [1], [1], [1]])

print(X.shape)

(4, 2)


In [20]:
def sigmoid(y):
    return 2.0/(1+np.exp(-y)) - 1.0

In [21]:
sigmoid(np.array([0, 1, 2]))

array([0.        , 0.46211716, 0.76159416])

In [34]:
def sigmoid_derivative(a):
    s = sigmoid(a)
    return 0.5 * (1-s) * (1+s)

In [35]:
np.random.seed(1000)
w = np.random.randn(2, 1)
b = np.zeros((1, 1))

print(w, w.shape)
print(b, b.shape)

[[-0.8044583 ]
 [ 0.32093155]] (2, 1)
[[0.]] (1, 1)


In [36]:
layer0 = X
y = np.dot(X, w) + b
layer1 = sigmoid(y)
print(y, y.shape)
print(np.dot(X, w))
print(layer1)

[[ 0.48352676]
 [ 1.12538985]
 [-1.12538985]
 [-0.48352676]] (4, 1)
[[ 0.48352676]
 [ 1.12538985]
 [-1.12538985]
 [-0.48352676]]
[[ 0.23716064]
 [ 0.50997422]
 [-0.50997422]
 [-0.23716064]]


In [37]:
def forward_compute(X, w, b):
    layer0 = X
    y = np.dot(X, w) + b
    layer1 = sigmoid(y)
    return layer0, layer1

In [38]:
np.dot(X, w), X.shape, w.shape

(array([[ 0.48352676],
        [ 1.12538985],
        [-1.12538985],
        [-0.48352676]]),
 (4, 2),
 (2, 1))

In [39]:
learning_rate = 0.1
layer0, layer1 = forward_compute(X, w, b)

decision = layer1.copy() 
decision[decision>=0] = 1
decision[decision<0] = -1
error = np.sum(np.abs(decision-z))
loss = np.sum(np.abs(layer1 - z))
print( error, loss, layer1.T)

layer1_error = layer1 - z
layer1_delta = layer1_error
# layer1_delta = layer1_error * sigmoid_derivative(layer1)

print(layer1_error)
print(layer1_delta)

6.0 4.47432128157507 [[ 0.23716064  0.50997422 -0.50997422 -0.23716064]]
[[ 1.23716064]
 [-0.49002578]
 [-1.50997422]
 [-1.23716064]]
[[ 1.23716064]
 [-0.49002578]
 [-1.50997422]
 [-1.23716064]]


In [40]:
print(X.T)
print(X.T.shape, layer1_delta.shape)
print(len(X))

[[-1 -1  1  1]
 [-1  1 -1  1]]
(2, 4) (4, 1)
4


In [47]:
learning_rate = 0.1
for epoch in range(1000):
    layer0, layer1 = forward_compute(X, w, b)

    decision = layer1.copy() 
    decision[decision>=0] = 1
    decision[decision<0] = -1
    error = np.sum(np.abs(decision-z))
    loss = np.sum(np.abs(layer1 - z))
    print(epoch, error, loss, layer1.T)
    # if error == 0: break

    layer1_error = layer1 - z
    layer1_delta = layer1_error * sigmoid_derivative(layer1)

    dw = np.dot(X.T, layer1_delta) / len(X)
    db = np.sum(layer1_delta) / len(X)

    w -= learning_rate * dw
    b -= learning_rate * db

0 0.0 2.732817625717717 [[-0.1617569   0.49516401  0.00126137  0.60900009]]
1 0.0 2.698764078871519 [[-0.17015266  0.49493136  0.01404291  0.622109  ]]
2 0.0 2.6657011517461044 [[-0.17835757  0.49474193  0.02655047  0.63464889]]
3 0.0 2.6335896888134744 [[-0.18637838  0.49459632  0.03878743  0.64664818]]
4 0.0 2.6023920341817104 [[-0.19422156  0.49449496  0.05075753  0.65813391]]
5 0.0 2.5720720229161937 [[-0.20189325  0.49443814  0.06246482  0.66913176]]
6 0.0 2.54259496090111 [[-0.20939935  0.49442596  0.07391362  0.6796661 ]]
7 0.0 2.5139275959148577 [[-0.21674548  0.49445841  0.08510847  0.68976005]]
8 0.0 2.4860380820996095 [[-0.22393701  0.49453533  0.09605408  0.6994355 ]]
9 0.0 2.458895939594857 [[-0.23097906  0.49465647  0.10675533  0.7087132 ]]
10 0.0 2.43247201076487 [[-0.23787652  0.49482148  0.11721722  0.71761277]]
11 0.0 2.4067384141695083 [[-0.24463409  0.49502989  0.12744483  0.72615279]]
12 0.0 2.3816684971972393 [[-0.25125622  0.49528117  0.13744329  0.73435082]]
13 

In [48]:
w, b

(array([[3.05613628],
        [3.05622334]]),
 array([[3.05620153]]))

In [49]:
inputs, hiddens, outputs = 2, 2, 1
W1 = np.random.randn(inputs, hiddens) + 0.5
W2 = np.random.randn(hiddens, outputs) + 0.5
b1 = np.zeros(hiddens)
b2 = np.zeros(outputs)

In [50]:
print(W1, W2, b1, b2)

[[ 1.0950355   0.03533247]
 [ 1.16728131 -0.30611561]] [[-0.69606983]
 [ 0.09403984]] [0. 0.] [0.]


In [51]:
def prediction(X, W1, W2, b1, b2):
    layer0 = X
    y1 = np.dot(X, W1) + b1
    layer1 = sigmoid(y1)
    y2 = np.dot(layer1, W2) + b2
    layer2 = sigmoid(y2)
    return layer0, layer1, layer2

In [52]:
learning_rate = 5
for epoch in range(10000):
    # prediction
    layer0, layer1, layer2 = prediction(X, W1, W2, b1, b2)
    z_2_hat = layer2

    # check break condition
    decision = z_2_hat >= 0.5
    error = np.sum(np.abs(decision-z))
    print(epoch, error, z_2_hat.T)
    if error == 0:
        break

    # Backpropagation
    layer2_error = layer2 - z
    layer2_delta = layer2_error * sigmoid_derivative(layer2)
    dW2 = np.dot(layer1.T, layer2_delta) / len(layer2_delta)
    db2 = np.sum(layer2_delta, axis=0) / len(layer2_delta)

    layer1_error = np.dot(layer2_delta, W2.T)
    layer1_delta = layer1_error * sigmoid_derivative(layer1)
    dW1 = np.dot(layer0.T, layer1_delta) / len(layer1_delta)
    db1 = np.sum(layer1_delta, axis=0) / len(layer1_delta)

    # Update
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

0 4 [[ 0.28096398 -0.02051403  0.02051403 -0.28096398]]
1 2 [[0.3923143  0.52194856 0.49570564 0.63431109]]
2 3 [[0.11840399 0.46467646 0.42002162 0.74329839]]
3 3 [[-0.12751277  0.49779178  0.45350964  0.8766344 ]]
4 1 [[-0.32044808  0.58056441  0.56186478  0.94187552]]
5 1 [[-0.47955632  0.6735511   0.66967948  0.96914635]]
6 1 [[-0.60219552  0.75325578  0.74960267  0.98154886]]
7 1 [[-0.68984988  0.81037041  0.80682575  0.9878269 ]]
8 1 [[-0.75158978  0.84995775  0.84667065  0.99133648]]
9 1 [[-0.79572986  0.87783904  0.87483227  0.99347447]]
10 1 [[-0.8281385   0.89803879  0.89529761  0.99487072]]
11 1 [[-0.85260712  0.91311869  0.91061609  0.99583446]]
12 1 [[-0.87156254  0.92469132  0.9223987   0.99652969]]
13 1 [[-0.88658385  0.9337901   0.93168109  0.99704942]]
14 1 [[-0.89872426  0.94109519  0.93914672  0.99744943]]
15 1 [[-0.90870496  0.94706697  0.94525929  0.99776484]]
16 1 [[-0.91703242  0.95202553  0.95034184  0.99801865]]
17 1 [[-0.92407063  0.95619893  0.954625    0.998