In [11]:
import numpy as np

In [12]:
X = np.array([[-1, -1], [-1, 1], [1, -1], [1, 1]])
z = np.array([[-1], [1], [1], [1]])

In [13]:
def sigmoid(y):
    return 2.0/(1+np.exp(-y)) - 1.0

In [14]:
def sigmoid_derivative(y):
    z = sigmoid(y)
    return 0.5 * (1-z) * (1+z)

In [15]:
np.random.seed(1000)
w = np.random.randn(2, 1)
b = np.zeros((1, 1))

In [16]:
def forward_compute(X, w, b):
    layer0 = X
    y = np.dot(X, w) + b
    layer1 = sigmoid(y)
    return layer0, layer1

In [17]:
np.dot(X, w), X.shape, w.shape

(array([[ 0.48352676],
        [ 1.12538985],
        [-1.12538985],
        [-0.48352676]]),
 (4, 2),
 (2, 1))

In [18]:
learning_rate = 0.1
for epoch in range(1000):
    layer0, layer1 = forward_compute(X, w, b)

    decision = layer1.copy() # copy 붙인거하고 않붙인거 차이 있음
    decision[decision>=0] = 1
    decision[decision<0] = -1
    error = np.sum(np.abs(decision-z))
    loss = np.sum(np.abs(layer1 - z))
    print(epoch, error, loss, layer1.T)
    # if error == 0: break

    layer1_error = layer1 - z
    layer1_delta = layer1_error * sigmoid_derivative(layer1)

    dw = np.dot(X.T, layer1_delta) / len(X)
    db = np.sum(layer1_delta) / len(X)

    w -= learning_rate * dw
    b -= learning_rate * db

0 6.0 4.47432128157507 [[ 0.23716064  0.50997422 -0.50997422 -0.23716064]]
1 6.0 4.398743244164938 [[ 0.21936267  0.50980119 -0.49224474 -0.19693702]]
2 6.0 4.32341578849316 [[ 0.20183437  0.50958955 -0.47434502 -0.15682594]]
3 6.0 4.248583319307009 [[ 0.18460046  0.50933661 -0.45630967 -0.1170098 ]]
4 6.0 4.17447283022238 [[ 0.16768223  0.50904068 -0.43817331 -0.07765796]]
5 6.0 4.101290418395967 [[ 0.1510975   0.50870103 -0.41997018 -0.03892378]]
6 6.0 4.029218849874559 [[ 0.13486053  0.50831798 -0.40173368 -0.00094261]]
7 4.0 3.9584161786477567 [[ 0.11898221  0.50789274 -0.38349611  0.0361694 ]]
8 4.0 3.889015347087032 [[ 0.10347016  0.50742741 -0.3652883   0.0723157 ]]
9 4.0 3.8211246394463556 [[ 0.08832899  0.50692486 -0.34713947  0.10741896]]
10 4.0 3.7548288261561242 [[ 0.07356058  0.50638861 -0.32907701  0.14142015]]
11 4.0 3.690190823782242 [[ 0.05916437  0.50582269 -0.3111264   0.17427726]]
12 4.0 3.6272537001497387 [[ 0.04513768  0.50523155 -0.29331116  0.20596359]]
13 4.0 3

In [19]:
w, b

(array([[3.02712441],
        [3.02722208]]),
 array([[3.02719761]]))